### ISSUE TITLE
Mails sent by Formicular are not in HTML format

### ISSUE THREAD

**Issue by ThiloWitt** [zikula-modules/Formicula#89]
Mails sent by Formicular are not in HTML format as set in the form. All form entry data come flat, one after another without separators. Example:

Hello! A visitor of to your web site used the form for contact and sent the following: Form #: 1 Contact: Webmaster Name: SASDFASF Company: asdf Email: webmaster@tASFDAa.eu Location: adsf Apply as: asfd Date of birth: 12/12/1980 Street: asdf Desired salary: 123121 Entry date: 123118 Comment: qwead The user has the following IP address/hostname: .......................t-ipconnect.de

**Comment by Guite** [comment]
Thanks. Fixed in https://github.com/zikula-modules/Formicula/commit/bd633d4727d8b5b39adf3a0d8831536579450d62
